import {Film} from '../types/Film';
import {GenresListProps} from '../components/genres-list/genres-list';

const films: Film[] = [
  {poster: 'img/fantastic-beasts-the-crimes-of-grindelwald.jpg',
    name: 'Fantastic Beasts: The Crimes of Grindelwald',
    isFavorite: true},
  {poster: 'img/bohemian-rhapsody.jpg',
    name: 'Bohemian Rhapsody',
    isFavorite: true},
  {poster:'img/macbeth.jpg',
    name:'Macbeth',
    isFavorite: true},
  {poster:'img/aviator.jpg',
    name:'Aviator',
    isFavorite: true},
  {poster:'img/we-need-to-talk-about-kevin.jpg',
    name:'We need to talk about Kevin',
    isFavorite: true},
  {poster:'img/what-we-do-in-the-shadows.jpg',
    name:'What We Do in the Shadows',
    isFavorite: false},
  {poster:'img/revenant.jpg',
    name:'Revenant',
    isFavorite: false},
  {poster:'img/johnny-english.jpg',
    name:'Johnny English,',
    isFavorite: false},
  {poster:'img/shutter-island.jpg',
    name:'Shutter Island',
    isFavorite: false},
  {poster:'img/pulp-fiction.jpg',
    name:'Pulp Fiction',
    isFavorite: false},
  {poster:'img/no-country-for-old-men.jpg',
    name:'No Country for Old Men',
    isFavorite: false},
  {poster:'img/snatch.jpg',
    name:'Snatch',
    isFavorite: false},
  {poster:'img/moonrise-kingdom.jpg',
    name:'Moonrise Kingdom',
    isFavorite: false},
  {poster:'img/seven-years-in-tibet.jpg',
    name:'Seven Years in Tibet',
    isFavorite: false},
  {poster:'img/midnight-special.jpg',
    name:'Midnight Special',
    isFavorite: false},
  {poster:'img/war-of-the-worlds.jpg',
    name:'War of the Worlds',
    isFavorite: false},
  {poster:'img/dardjeeling-limited.jpg',
    name:'Dardjeeling Limited',
    isFavorite: false},
  {poster:'img/orlando.jpg',
    name:'Orlando',
    isFavorite: false},
  {poster:'img/mindhunter.jpg',
    name:'Mindhunter',
    isFavorite: false},
  {poster:'img/midnight-special.jpg',
    name:'Midnight Special',
    isFavorite: false},
];

const genres: GenresListProps =
  {
    genres: ['All genres', 'Comedies', 'Crime', 'Documentary', 'Dramas', 'Horror', 'Kids & Family', 'Romance', 'Sci-Fi', 'Thrillers'],
    currentActive: 'All genres'
  };


export {films, genres};
